### ISSUE TITLE
About export_onnx!

### ISSUE THREAD

**Issue by sunmooncode** [kevinleestone/mmstereo#1]
Can the onnx model be converted to the result of the operator without adding tensorrt?

**Comment by sunmooncode** [comment]
@PINTO0309 Are you interested！

**Comment by PINTO0309** [comment]
I am interested in this repository, but have no plans to do anything with it at this time because the checkpoints are not open to the public.

By the way, I successfully completed CREStereo's TensorRT full mapping yesterday.
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/284_CREStereo
